### ISSUE TITLE
Return an enum if no block its given 

### ISSUE THREAD

**Issue by JuanPabloGil** [Israel-Laguan/Advanced-Building-Blocks---Enumerables#3]
You need to return an enum if no block it is given, not a raise. I will recommend you to read this article in SO for more info (https://stackoverflow.com/questions/19499066/how-does-to-enummethod-receive-its-block-here)

https://github.com/Israel-Laguan/Advanced-Building-Blocks---Enumerables/blob/340c2dfd09dbf3ce5f601934360f620a124d349a/lib/enumerable/each.rb#L4-L5

**Comment by Israel-Laguan** [comment]
Done, thanks for suggestion!
